#  fixoutput.py
#  This file fixes the output generated by the cluster since it uses an
#  older version of numpy.

import fileinput
from glob import glob

def main():
    folder = '/Users/k9s/Documents/ObjectiveMethod/MOEPSO/Static/SBSBPP500/Experiment01/amaxweight/'
    flag = 'SwarmMember178/gen31/'
    fixxy(folder, flag)


def fixxy(folder, flag):
    xfiles = glob(folder + flag + '*_x.txt')
    yfiles = glob(folder + flag + '*_y.txt')
    numsols = len(xfiles)
    for m in range(numsols):
        for xlinenum, xline in enumerate(fileinput.FileInput(xfiles[m], inplace=1)):
            if xlinenum == 0:
                print('# Item Location Matrix x:')
                print(xline.rstrip())
            else:
                print(xline.rstrip())
        for ylinenum, yline in enumerate(fileinput.FileInput(yfiles[m], inplace=1)):
            if ylinenum == 0:
                print('# Bins Used Matrix y:')
                print(yline.rstrip())
            else:
                print(yline.rstrip())


def unfix(folder, flag):
    xfiles = glob(folder + flag + '*_x.txt')
    yfiles = glob(folder + flag + '*_y.txt')
    numsols = len(xfiles)
    for m in range(numsols):
        for xlinenum, xline in enumerate(fileinput.FileInput(xfiles[m], inplace=1)):
            if xlinenum != 0:
                print(xline.rstrip())
        for ylinenum, yline in enumerate(fileinput.FileInput(yfiles[m], inplace=1)):
            if ylinenum != 0:
                print(yline.rstrip())


if __name__ == '__main__':
    main()
