# separate.py
#    Program to sort through files generated by 2DCPackGen
#    and separate into individual experiments.
#    Author: Kristina Spencer
#    Date: February 26, 2016


def main():
    file = input("Please enter the location/name of the file: ")
    y, runs = getruns(file)
    infile = open(file, "r")
    for line in infile:
        x = infile.readline()
        if x == y: break
    for i in range(runs):
        runfile = file[:-5] + str(i+1) + '.txt'
        outfile = open(runfile, "w")
        z = infile.readline()
        print(z, file=outfile)
        n = int(infile.readline())
        for j in range(n):
            z = infile.readline()
            print(z, file=outfile)
        outfile.close()
    infile.close()


def getruns(input):
    import linecache
    y = linecache.getline(input, 10)
    runs = int(y)
    return y, runs

main()
